export const GET_ALL_RECIPES =  "GET_ALL_RECIPES"
export const GET_RECIPE_DETAIL =  "GET_RECIPE_DETAIL"
export const GET_DIET_TYPES =  "GET_DIET_TYPES"
export const CREATE_RECIPE = "CREATE_RECIPE"
export const SEARCH_RECIPE = "SEARCH_RECIPE"
export const FILTER_RECIPES_BY_TYPE = "FILTER_RECIPES_BY_TYPE"
export const RESET_RECIPES = "RESET_RECIPES"
export const ORDER_RECIPES = "ORDER_RECIPES"


